"""add area, venue, venue_contact, saved_venue

Revision ID: 1935efcb542b
Revises: 
Create Date: 2026-08-30 08:37:32.400750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1935efcb542b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_area_dedupe', 'area', [sa.literal_column('round(lat, 4)'), sa.literal_column('round(lon, 4)'), 'radius_m'], unique=True)
    op.create_table('venue',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('area_id', sa.BigInteger(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('osm_type', sa.Enum('node', 'way', 'relation', name='osm_type'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('osm_phone', sa.String(), nullable=True),
    sa.Column('osm_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'osm_id', 'osm_type', name='uq_venue_area_osm')
    )
    op.create_table('saved_venue',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'venue_id', name='uq_saved_venue_user_venue')
    )
    op.create_table('venue_contact',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('booking_url', sa.String(), nullable=True),
    sa.Column('scrape_status', sa.Enum('success', 'no_website', 'timeout', 'disallowed_by_robots', 'error', name='scrape_status'), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_contact')
    op.drop_table('saved_venue')
    op.drop_table('venue')
    op.drop_index('ix_area_dedupe', table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
    sa.Enum(name='scrape_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='osm_type').drop(op.get_bind(), checkfirst=True)
